#
# Copyright 2010 Nexell Co.
#
# Makefile for the Nexell misc drivers

obj-$(CONFIG_MISC_NEXELL_ADC)	+= adc.o
obj-$(CONFIG_MISC_NEXELL_PWM)	+= pwm.o
obj-$(CONFIG_MISC_NEXELL_PMI)	+= pmi.o
obj-$(CONFIG_MISC_NEXELL_SPI)	+= spi.o
obj-$(CONFIG_MISC_NEXELL_GPIO)	+= gpio.o
obj-$(CONFIG_MISC_NEXELL_DIBDXB)	+= dib_dxb.o
obj-$(CONFIG_MISC_NEXELL_TIMER_90K)	+= timer_90k.o
obj-$(CONFIG_MISC_NEXELL_MPEGTS)	+= mpegts.o
obj-$(CONFIG_MISC_NEXELL_GPIOMON)	+= gpiomon.o
obj-$(CONFIG_MISC_NEXELL_VSTATION)	+= vstation.o
obj-$(CONFIG_MISC_NEXELL_BUZZER)	+= buzzer.o
