#include "ioc_magic.h"

enum
{
	IOCTL_MPEGTS_RUN	=	_IO(IOC_NX_MAGIC, 1),
	IOCTL_MPEGTS_STOP	=	_IO(IOC_NX_MAGIC, 2),
	IOCTL_MPEGTS_CON_BUF	=	_IO(IOC_NX_MAGIC, 3),
	IOCTL_MPEGTS_READ_BUF_STATUS =	_IO(IOC_NX_MAGIC, 4),
};
